### ISSUE TITLE
NSX-v 6.4 VXLAN Prep fails

### ISSUE THREAD

**Issue by yfauser** [vmware/nsxansible#68]
TASK [Cluster VXLAN Preparation] ***********************************************
task path: /home/vmware/ansible/nsx_vxlan_prep.yml:8
Using module file /home/vmware/ansible/library/nsx_vxlan_prep.py
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: vmware
<127.0.0.1> EXEC /bin/sh -c 'echo ~ && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/vmware/.ansible/tmp/ansible-tmp-1517868644.69-181174024177698 `" && echo ansible-tmp-1517868644.69-181174024177698="` echo /home/vmware/.ansible/tmp/ansible-tmp-1517868644.69-181174024177698 `" ) && sleep 0'
<127.0.0.1> PUT /tmp/tmpYuaXw7 TO /home/vmware/.ansible/tmp/ansible-tmp-1517868644.69-181174024177698/nsx_vxlan_prep.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /home/vmware/.ansible/tmp/ansible-tmp-1517868644.69-181174024177698/ /home/vmware/.ansible/tmp/ansible-tmp-1517868644.69-181174024177698/nsx_vxlan_prep.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python /home/vmware/.ansible/tmp/ansible-tmp-1517868644.69-181174024177698/nsx_vxlan_prep.py; rm -rf "/home/vmware/.ansible/tmp/ansible-tmp-1517868644.69-181174024177698/" > /dev/null 2>&1 && sleep 0'
fatal: [localhost]: FAILED! => {
    "changed": false, 
    "module_stderr": "receive bad status code 500\n{'error': {'errorCode': '100'}}\n", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE", 
    "rc": 0
}
    to retry, use: --limit @/home/vmware/ansible/nsx_vxlan_prep.retry
 
PLAY RECAP *********************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1

**Comment by nickliuibm** [comment]
Hello, Yves, 

I hit the exact same failure when I play around with NSX 6.4.1.  I tried your fix in https://github.com/vmware/nsxansible/commit/f7ccc52591c61ab9bf0dfbcd9c836c446e65c9a8. but it does not work, I still see the same failure after applying the fix. 

Do you have any advise?

**Comment by yfauser** [comment]
Hi @nickliuibm 

I also had to fix a little detail in the nsxramlclient (https://github.com/vmware/nsxramlclient/issues/22).

What version of nsxramlclient are you using? If it is not the latest one, can you try to upgrade it?

Cheers

**Comment by nickliuibm** [comment]
Thanks Yves for your help.

I already installed the latest nsxramclient, what I am using is 2.0.7. 

Actually, I hit a couple issues with our code which was working for NSX 6.3.5 after I started using NSX 6.4.1; most of them have been addressed except for this one, including
1.  Deploy ova failure because of `--net` changed to `Management Network=`
2. Register NSX Manager to vCenter failure because of thumprint changed to `sha256`
3. Create controller failure because the return code changed to 202. 

However this cluster preparation failure ran out of my idea for the fix.  I tried the fix in https://github.com/vmware/nsxansible/commit/f7ccc52591c61ab9bf0dfbcd9c836c446e65c9a8, updated nsxclient to the latest 2.0.7 and also updated nsxraml to the latest https://github.com/vmware/nsxraml/blob/master/nsxvapi.raml.  I still cannot get pass this failure.

Not sure if this is helpful, but  I noticed no matter what I tried above, I always see the following failure in NSX manager log. 

```
2018-05-31 23:18:04.120 GMT  INFO http-nio-127.0.0.1-7441-exec-3 LicenseAssignmentManagerHelper:634 - - [nsxv@6876 comp="nsx-manager" subcomp="manager"] Refresh not needed. Using cached features
2018-05-31 23:18:04.120 GMT  INFO http-nio-127.0.0.1-7441-exec-3 LicenseAssignmentManagerHelper:642 - - [nsxv@6876 comp="nsx-manager" subcomp="manager"] Returning features = [vxlan, nat, routing, endpoint, swbridge, edgefw, aagw, trcflow, dhcp]
2018-05-31 23:18:04.120 GMT  INFO http-nio-127.0.0.1-7441-exec-3 LicenseAssignmentManagerHelper:704 - - [nsxv@6876 comp="nsx-manager" subcomp="manager"] Returning isAVOnlyLicenseAssigned = false
2018-05-31 23:18:04.144 GMT ERROR http-nio-127.0.0.1-7441-exec-3 BaseRestController:518 - - [nsxv@6876 comp="nsx-manager" subcomp="manager"] REST API failed : 'null'
java.lang.NullPointerException: null
        at com.vmware.vshield.vsm.vdn.service.FabricIntegrationImpl$VxlanFeaturePlugin.getLagNames_aroundBody0(FabricIntegrationImpl.java:914) ~[vsphere-1.0.jar:?]
        at com.vmware.vshield.vsm.vdn.service.FabricIntegrationImpl$VxlanFeaturePlugin$AjcClosure1.run(FabricIntegrationImpl.java:1) ~[vsphere-1.0.jar:?]
        at org.springframework.transaction.aspectj.AbstractTransactionAspect.ajc$around$org_springframework_transaction_aspectj_AbstractTransactionAspect$1$2a73e96cproceed(AbstractTransactionAspect.aj:66) ~[spring-aspects-4.3.14.RELEASE.jar:4.3.14.RELEASE]
        at org.springframework.transaction.aspectj.AbstractTransactionAspect$AbstractTransactionAspect$1.proceedWithInvocation(AbstractTransactionAspect.aj:72) ~[spring-aspects-4.3.14.RELEASE.jar:4.3.14.RELEASE]
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:282) ~[spring-tx-4.3.14.RELEASE.jar:4.3.14.RELEASE]
        at org.springframework.transaction.aspectj.AbstractTransactionAspect.ajc$around$org_springframework_transaction_aspectj_AbstractTransactionAspect$1$2a73e96c(AbstractTransactionAspect.aj:70) ~[spring-aspects-4.3.14.RELEASE.jar:4.3.14.RELEASE]
        at com.vmware.vshield.vsm.vdn.service.FabricIntegrationImpl$VxlanFeaturePlugin.getLagNames(FabricIntegrationImpl.java:913) ~[vsphere-1.0.jar:?]
        at com.vmware.vshield.vsm.vdn.service.FabricIntegrationImpl$VxlanFeaturePlugin.validate(FabricIntegrationImpl.java:904) ~[vsphere-1.0.jar:?]
        at com.vmware.vshield.vsm.nwfabric.service.impl.NetworkPrepServiceImpl.runValidation(NetworkPrepServiceImpl.java:402) ~[vsphere-1.0.jar:?]
        at com.vmware.vshield.vsm.nwfabric.service.impl.NetworkPrepServiceImpl.addFeature_aroundBody0(NetworkPrepServiceImpl.java:114) ~[vsphere-1.0.jar:?]
        at com.vmware.vshield.vsm.nwfabric.service.impl.NetworkPrepServiceImpl$AjcClosure1.run(NetworkPrepServiceImpl.java:1) ~[vsphere-1.0.jar:?]
        at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149) ~[aspectjweaver-1.8.9.jar:1.8.9]
        at com.vmware.vshield.vsm.aspects.security.VsmSecuredAspect.secureCheck(VsmSecuredAspect.java:134) ~[vsm-core-1.0.jar:?]
        at com.vmware.vshield.vsm.aspects.security.VsmSecuredAspect.ajc$inlineAccessMethod$com_vmware_vshield_vsm_aspects_security_VsmSecuredAspect$com_vmware_vshield_vsm_aspects_security_VsmSecuredAspect$secureCheck(VsmSecuredAspect.java:1) ~[vsm-core-1.0.jar:?]
        at com.vmware.vshield.vsm.aspects.security.VsmSecuredAspect.secure(VsmSecuredAspect.java:66) ~[vsm-core-1.0.jar:?]
        at com.vmware.vshield.vsm.nwfabric.service.impl.NetworkPrepServiceImpl.addFeature(NetworkPrepServiceImpl.java:102) ~[vsphere-1.0.jar:?]
        at com.vmware.vshield.vsm.nwfabric.facade.impl.NetworkPrepFacadeImpl.addFeature(NetworkPrepFacadeImpl.java:123) ~[vsphere-1.0.jar:?]
        at com.vmware.vshield.vsm.nwfabric.restcontroller.NetworkPrepController.processConfigureRequest(NetworkPrepController.java:83) ~[vsphere-1.0.jar:?]
        at com.vmware.vshield.vsm.nwfabric.restcontroller.NetworkPrepController.processConfigurePostRequest_aroundBody0(NetworkPrepController.java:55) ~[vsphere-1.0.jar:?]
        at com.vmware.vshield.vsm.nwfabric.restcontroller.NetworkPrepController$AjcClosure1.run(NetworkPrepController.java:1) ~[vsphere-1.0.jar:?]
        at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:221) ~[aspectjweaver-1.8.9.jar:1.8.9]
        at com.vmware.vshield.vsm.aspects.web.RequestBodyValidatorAspect.aroundController(RequestBodyValidatorAspect.java:50) ~[vsm-core-1.0.jar:?]
        at com.vmware.vshield.vsm.nwfabric.restcontroller.NetworkPrepController.processConfigurePostRequest(NetworkPrepController.java:49) ~[vsphere-1.0.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_161]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_161]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_161]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_161]
        at org.springframework.web.bind.annotation.support.HandlerMethodInvoker.invokeHand
```

**Comment by yfauser** [comment]
Hi @nickliuibm,

please contact me at yfauser@vmware.com. I think its faster to look at your Setup in a Zoom session. 

- Yves
